### ISSUE TITLE
swift accounting

### ISSUE THREAD

**Issue by craigpatten** [eResearchSA/reporting-producers#30]
I wrote a prototype for [swift accounting](https://gist.github.com/craigpatten/5d20c007903f13e9f557). Not sure whether you want to put it in [openstack.py](/eResearchSA/reporting-producers/blob/master/reporting/plugins/openstack.py) or a new file, but I'm easy either way.

It needs to run on a swift box so it can access (i) the current account ring and (ii) the swift storage boxes, over which it spreads the HTTP HEAD requests.

CC @ahill-ersa FYI

**Comment by Li-ReDBox** [comment]
all people are gone, swift is not interested to eRSA.
